### ISSUE TITLE
author picture uploader broken

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#1278]

**Comment by marcellosachs** [comment]
worked on this for about 40 minutes but there was no easy solution.
seems it has to do with the fact that this step - https://github.com/empirical-org/Empirical-Core/blob/98813c9bdd88226dbfc908906afdbcc458b7ccd8/app/assets/javascripts/modules/server/params.jsx#L6

is converting the FormData object into JSON, but FormData cannot really be turned into JSON.
just ends up as "{}"

If i remove that step entirely, Rails gets an error when receiving the POST request.

```

------WebKitFormBoundarydFHMfgGCSWSZmeBZ--


JSON::ParserError - 822: unexpected token at '------WebKitFormBoundarydFHMfgGCSWSZmeBZ
Content-Disposition: form-data; name="author[name]"

testname
------WebKitFormBoundarydFHMfgGCSWSZmeBZ
Content-Disposition: form-data; name="author[avatar]"; filename="promotional_large_920x680.png"
Content-Type: image/png

�PNG

':
  /Users/marcellomarcellosachs/code/.rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
  activesupport (4.2.5.1) lib/active_support/json/decoding.rb:26:in `decode'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:44:in `parse_formatted_parameters'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:23:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.1) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  sentry-raven (0.15.4) lib/raven/integrations/rack.rb:53:in `call'
  rack-heartbeat (1.0.1) lib/rack/heartbeat.rb:27:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.16.0) lib/puma/server.rb:557:in `handle_request'
  puma (2.16.0) lib/puma/server.rb:404:in `process_client'
  puma (2.16.0) lib/puma/server.rb:270:in `block in run'
  puma (2.16.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by petergault** [comment]
@marcellosachs @RyanNovas I would like to move to hard coded images, like the Team page. Images are stored in the assets folder and connected via a hard-coding.

**Comment by marcellosachs** [comment]
randomly realized what's wrong here, clued in by the fact that the error mentions JSON but the formData should be processed as JSON. basically have to set contentType=false processData=false in the ajax params. this is already handled by the code, but theres downstream code that overrides it and sets contentType=json (remember adding that in a few months ago mistakenly). should be able to fix this in about 15 minutes.
