### ISSUE TITLE
Fix last remaining failing test

### ISSUE THREAD

**Issue by jaredsilver** [empirical-org/Empirical-Core#2339]
```
1) Signing up a Teacher with new info send_newsletter is true marks it appropriately
     Failure/Error: current_user.schools << school
     
     NoMethodError:
       undefined method `schools' for nil:NilClass
     # ./app/controllers/accounts_controller.rb:50:in `select_school'
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   /home/travis/build/empirical-org/Empirical-Core/vendor/bundle/ruby/2.3.0/gems/capybara-2.10.0/lib/capybara/session.rb:126:in `raise_server_error!'
```

https://travis-ci.org/empirical-org/Empirical-Core/builds/211503515#L2435-L2445

**Comment by emilia-friedberg** [comment]
@jaredsilver you can do it!
