### ISSUE TITLE
foreman start -f Procfile.static not running

### ISSUE THREAD

**Issue by rja907** [empirical-org/Empirical-Core#4020]
## Expected Behaviour
It should run the server and let me run the app in DEV mode.

## Actual Behaviour
It just sends a SIGTERM to all processes and doesn't serve.
This is the result on the terminal:

```
Rajs-MacBook-Pro:Empirical-Core raj$ foreman start -f Procfile.static
16:02:19 rails.1               | started with pid 1303
16:02:19 worker.1              | started with pid 1304
16:02:19 rails-client-assets.1 | started with pid 1305
16:02:19 rails-server-assets.1 | started with pid 1306
16:02:19 redis-sidekiq.1       | started with pid 1307
16:02:19 redis-testing.1       | started with pid 1308
16:02:19 redis-caching.1       | 1309:C 18 Mar 16:02:19.708 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
16:02:19 redis-sidekiq.1       | 1307:C 18 Mar 16:02:19.702 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
16:02:19 redis-testing.1       | 1308:C 18 Mar 16:02:19.702 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
16:02:19 redis-caching.1       | 1309:C 18 Mar 16:02:19.709 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1309, just started
16:02:19 redis-sidekiq.1       | 1307:C 18 Mar 16:02:19.704 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1307, just started
16:02:19 redis-testing.1       | 1308:C 18 Mar 16:02:19.706 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1308, just started
16:02:19 redis-caching.1       | 1309:C 18 Mar 16:02:19.709 # Configuration loaded
16:02:19 redis-sidekiq.1       | 1307:C 18 Mar 16:02:19.704 # Configuration loaded
16:02:19 redis-testing.1       | 1308:C 18 Mar 16:02:19.706 # Configuration loaded
16:02:19 redis-caching.1       | 1309:M 18 Mar 16:02:19.710 * Increased maximum number of open files to 10032 (it was originally set to 256).
16:02:19 redis-sidekiq.1       | 1307:M 18 Mar 16:02:19.705 * Increased maximum number of open files to 10032 (it was originally set to 256).
16:02:19 redis-testing.1       | 1308:M 18 Mar 16:02:19.707 * Increased maximum number of open files to 10032 (it was originally set to 256).
16:02:19 redis-caching.1       | 1309:M 18 Mar 16:02:19.712 * Running mode=standalone, port=7654.
16:02:19 redis-sidekiq.1       | 1307:M 18 Mar 16:02:19.710 * Running mode=standalone, port=6379.
16:02:19 redis-testing.1       | 1308:M 18 Mar 16:02:19.710 * Running mode=standalone, port=6378.
16:02:19 redis-caching.1       | 1309:M 18 Mar 16:02:19.712 # Server initialized
16:02:19 redis-sidekiq.1       | 1307:M 18 Mar 16:02:19.710 # Server initialized
16:02:19 redis-testing.1       | 1308:M 18 Mar 16:02:19.710 # Server initialized
16:02:19 redis-caching.1       | 1309:M 18 Mar 16:02:19.712 * Ready to accept connections
16:02:19 redis-sidekiq.1       | 1307:M 18 Mar 16:02:19.710 * Ready to accept connections
16:02:19 redis-testing.1       | 1308:M 18 Mar 16:02:19.710 * Ready to accept connections
16:02:19 redis-caching.1       | started with pid 1309
16:02:20 rails-client-assets.1 | 
16:02:20 rails-client-assets.1 | > @ build:dev:client /Users/raj/Desktop/Empirical-Core
16:02:20 rails-server-assets.1 | 
16:02:20 rails-client-assets.1 | > (cd client && npm run build:dev:client --silent)
16:02:20 rails-server-assets.1 | > @ build:dev:server /Users/raj/Desktop/Empirical-Core
16:02:20 rails-client-assets.1 | 
16:02:20 rails-server-assets.1 | > (cd client && npm run build:dev:server --silent)
16:02:20 rails-server-assets.1 | 
16:02:21 rails-server-assets.1 | 
16:02:21 rails-server-assets.1 | Webpack is watching the files…
16:02:21 rails-server-assets.1 | 
16:02:22 rails-client-assets.1 | Webpack dev build for Rails
16:02:22 rails-client-assets.1 | 
16:02:22 rails-client-assets.1 | Webpack is watching the files…
16:02:22 rails-client-assets.1 | 
16:02:23 rails-server-assets.1 | Hash: 4e792d6ddf1ac233e502
16:02:23 rails-server-assets.1 | Version: webpack 3.11.0
16:02:23 rails-server-assets.1 | Time: 1480ms
16:02:23 rails-server-assets.1 |            Asset    Size  Chunks                    Chunk Names
16:02:23 rails-server-assets.1 | server-bundle.js  264 kB       0  [emitted]  [big]  main
16:02:23 rails-server-assets.1 |   [89] (webpack)/buildin/global.js 509 bytes {0} [built]
16:02:23 rails-server-assets.1 |  [124] multi babel-polyfill 28 bytes {0} [built]
16:02:23 rails-server-assets.1 |     + 325 hidden modules
16:02:25 rails-client-assets.1 | (node:1316) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
16:02:25 rails-client-assets.1 | parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
16:02:31 worker.1              | I, [2018-03-18T16:02:31.535728 #1304]  INFO -- sentry: ** [Raven] Raven 2.7.1 configured not to capture errors: DSN not set
16:02:32 worker.1              | W, [2018-03-18T16:02:32.147505 #1304]  WARN -- : [SKYLIGHT] [1.5.0] Running Skylight in development mode. No data will be reported until you deploy your app.
16:02:32 worker.1              | (To disable this message for all local apps, run `skylight disable_dev_warning`.)
16:02:32 rails.1               | W, [2018-03-18T16:02:32.148211 #1303]  WARN -- : [SKYLIGHT] [1.5.0] Running Skylight in development mode. No data will be reported until you deploy your app.
16:02:32 rails.1               | (To disable this message for all local apps, run `skylight disable_dev_warning`.)
16:02:32 worker.1              | Api key must be initialized
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/salesmachine-ruby-1.0.0/lib/salesmachine/api/client.rb:196:in `check_api_key!'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/salesmachine-ruby-1.0.0/lib/salesmachine/api/client.rb:28:in `initialize'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/salesmachine-ruby-1.0.0/lib/salesmachine/api.rb:15:in `new'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/salesmachine-ruby-1.0.0/lib/salesmachine/api.rb:15:in `initialize'
16:02:32 worker.1              | /Users/raj/Desktop/Empirical-Core/config/initializers/salesmachine.rb:5:in `new'
16:02:32 worker.1              | /Users/raj/Desktop/Empirical-Core/config/initializers/salesmachine.rb:5:in `<top (required)>'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
16:02:32 worker.1              | /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
16:02:32 worker.1              | /Users/raj/Desktop/Empirical-Core/config/environment.rb:5:in `<top (required)>'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/skylight-1.5.0/lib/skylight/probes.rb:81:in `require'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/skylight-1.5.0/lib/skylight/probes.rb:81:in `require'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/sidekiq-5.0.5/lib/sidekiq/cli.rb:254:in `boot_system'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/sidekiq-5.0.5/lib/sidekiq/cli.rb:54:in `run'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/sidekiq-5.0.5/bin/sidekiq:12:in `<top (required)>'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/bin/sidekiq:23:in `load'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/bin/sidekiq:23:in `<main>'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/bin/ruby_executable_hooks:15:in `eval'
16:02:32 worker.1              | /Users/raj/.rvm/gems/ruby-2.3.1@quill/bin/ruby_executable_hooks:15:in `<main>'
16:02:32 rails.1               | /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/salesmachine-ruby-1.0.0/lib/salesmachine/api/client.rb:196:in `check_api_key!': Api key must be initialized (ArgumentError)
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/salesmachine-ruby-1.0.0/lib/salesmachine/api/client.rb:28:in `initialize'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/salesmachine-ruby-1.0.0/lib/salesmachine/api.rb:15:in `new'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/salesmachine-ruby-1.0.0/lib/salesmachine/api.rb:15:in `initialize'
16:02:32 rails.1               | 	from /Users/raj/Desktop/Empirical-Core/config/initializers/salesmachine.rb:5:in `new'
16:02:32 rails.1               | 	from /Users/raj/Desktop/Empirical-Core/config/initializers/salesmachine.rb:5:in `<top (required)>'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
16:02:32 rails.1               | 	from /Users/raj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
16:02:32 rails.1               | 	from /Users/raj/Desktop/Empirical-Core/config/environment.rb:5:in `<top (required)>'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/skylight-1.5.0/lib/skylight/probes.rb:81:in `require'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/skylight-1.5.0/lib/skylight/probes.rb:81:in `require'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
16:02:32 rails.1               | 	from /Users/raj/Desktop/Empirical-Core/config.ru:3:in `block in <main>'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
16:02:32 rails.1               | 	from /Users/raj/Desktop/Empirical-Core/config.ru:in `new'
16:02:32 rails.1               | 	from /Users/raj/Desktop/Empirical-Core/config.ru:in `<main>'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/rack-1.6.8/lib/rack/server.rb:300:in `build_app_and_options_from_config'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/rack-1.6.8/lib/rack/server.rb:209:in `app'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/commands/server.rb:61:in `app'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/rack-1.6.8/lib/rack/server.rb:337:in `wrapped_app'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/commands/server.rb:78:in `start'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
16:02:32 rails.1               | 	from /Users/raj/.rvm/gems/ruby-2.3.1@quill/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
16:02:32 rails.1               | 	from bin/rails:4:in `require'
16:02:32 rails.1               | 	from bin/rails:4:in `<main>'
16:02:32 rails.1               | I, [2018-03-18T16:02:31.535736 #1303]  INFO -- sentry: ** [Raven] Raven 2.7.1 configured not to capture errors: DSN not set
16:02:32 rails.1               | => Booting Puma
16:02:32 rails.1               | => Rails 4.2.7.1 application starting in development on http://0.0.0.0:3000
16:02:32 rails.1               | => Run `rails server -h` for more startup options
16:02:32 rails.1               | => Ctrl-C to shutdown server
16:02:32 rails.1               | Exiting
16:02:32 worker.1              | exited with code 1
16:02:32 system                | sending SIGTERM to all processes
16:02:32 rails.1               | exited with code 1
16:02:32 redis-sidekiq.1       | 1307:signal-handler (1521369152) Received SIGTERM scheduling shutdown...
16:02:32 redis-testing.1       | 1308:signal-handler (1521369152) Received SIGTERM scheduling shutdown...
16:02:32 redis-caching.1       | 1309:signal-handler (1521369152) Received SIGTERM scheduling shutdown...
16:02:32 redis-sidekiq.1       | 1307:M 18 Mar 16:02:32.866 # User requested shutdown...
16:02:32 redis-sidekiq.1       | 1307:M 18 Mar 16:02:32.867 # Redis is now ready to exit, bye bye...
16:02:32 redis-testing.1       | 1308:M 18 Mar 16:02:32.921 # User requested shutdown...
16:02:32 redis-testing.1       | 1308:M 18 Mar 16:02:32.921 # Redis is now ready to exit, bye bye...
16:02:32 redis-caching.1       | 1309:M 18 Mar 16:02:32.928 # User requested shutdown...
16:02:32 redis-caching.1       | 1309:M 18 Mar 16:02:32.928 # Redis is now ready to exit, bye bye...
16:02:32 redis-caching.1       | exited with code 0
16:02:33 redis-testing.1       | exited with code 0
16:02:33 redis-sidekiq.1       | exited with code 0
16:02:33 rails-server-assets.1 | terminated by SIGTERM
16:02:33 rails-client-assets.1 | terminated by SIGTERM
```

## Potential sources for the issue (filename, new features ect.)
I had not made any changes to the code. I just merged my fork with this upstream. package-lock.json is the problem, I think. But I am not sure.

**Comment by pavsidhu** [comment]
I'm still for some reason getting this issue when running the start command.
