### ISSUE TITLE
Set up fails due to migration

### ISSUE THREAD

**Issue by mrvp194** [empirical-org/Empirical-Core#535]
Getting this error when running `rake empirical:setup`

```shell
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `update' for nil:NilClass/Users/apprentice/Desktop/Empirical-Core/db/migrate/20141014162137_add_app_name_to_classification.rb:6:in `change'
/Users/apprentice/Desktop/Empirical-Core/lib/tasks/setup.rake:15:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `update' for nil:NilClass
/Users/apprentice/Desktop/Empirical-Core/db/migrate/20141014162137_add_app_name_to_classification.rb:6:in `change'
/Users/apprentice/Desktop/Empirical-Core/lib/tasks/setup.rake:15:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by mrvp194** [comment]
I am fixing this issue now ...

**Comment by petergault** [comment]
Thanks for fixing this @mrvp194
