### ISSUE TITLE
ExecJS::ProgramError - Error: Parse Error: Line 73: Unexpected token else

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#945]
This error currently breaks `develop`. CC @marcellosachs.

```
ExecJS::ProgramError - Error: Parse Error: Line 73: Unexpected token else:
  execjs (2.6.0) lib/execjs/ruby_racer_runtime.rb:98:in `wrap_error'
  execjs (2.6.0) lib/execjs/ruby_racer_runtime.rb:47:in `rescue in block in call'
  execjs (2.6.0) lib/execjs/ruby_racer_runtime.rb:44:in `block in call'
  execjs (2.6.0) lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
  execjs (2.6.0) lib/execjs/ruby_racer_runtime.rb:73:in `lock'
  execjs (2.6.0) lib/execjs/ruby_racer_runtime.rb:43:in `call'
  react-rails (0.12.0.0) lib/react/jsx.rb:18:in `transform'
  react-rails (0.12.0.0) lib/react/jsx/template.rb:13:in `evaluate'
  tilt (2.0.1) lib/tilt/template.rb:96:in `render'
  sprockets (3.3.4) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
  sprockets (3.3.4) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.3.4) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.3.4) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.3.4) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.3.4) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.3.4) lib/sprockets/loader.rb:316:in `fetch_asset_from_dependency_cache'
  sprockets (3.3.4) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.3.4) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.3.4) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.3.4) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.3.4) lib/sprockets/utils.rb:183:in `dfs'
  sprockets (3.3.4) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.3.4) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.3.4) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.3.4) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.3.4) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.3.4) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.3.4) lib/sprockets/loader.rb:316:in `fetch_asset_from_dependency_cache'
  sprockets (3.3.4) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.3.4) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.3.4) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.3.4) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.3.4) lib/sprockets/environment.rb:30:in `find_asset'
  sprockets (3.3.4) lib/sprockets/base.rb:92:in `[]'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:138:in `block in javascript_include_tag'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:136:in `javascript_include_tag'
  app/views/layouts/application.html.erb:9:in `_app_views_layouts_application_html_erb__2423744569889710339_70358592603220'
  actionview (4.1.13) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.13) lib/active_support/notifications.rb:161:in `instrument'
  actionview (4.1.13) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.13) lib/action_view/template.rb:143:in `render'
  actionview (4.1.13) lib/action_view/renderer/template_renderer.rb:67:in `render_with_layout'
  actionview (4.1.13) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.13) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.13) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.13) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.13) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.13) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.13) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.13) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.13) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.13) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.13) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.13) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.1.13) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/kriskelly/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.1.13) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.13) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.1.13) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.1.13) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.13) lib/action_controller/metal/instrumentation.rb:43:in `render'
  app/controllers/profiles_controller.rb:34:in `student'
  app/controllers/profiles_controller.rb:6:in `show'
  actionpack (4.1.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.13) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.13) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.13) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.13) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.13) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.13) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.13) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.13) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.13) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.13) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.13) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.13) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.13) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.13) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.13) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.13) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.13) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.13) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.13) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.13) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.13) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.13) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.13) lib/action_dispatch/routing/route_set.rb:692:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
  bullet (4.14.7) lib/bullet/rack.rb:12:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.13) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.13) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.13) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.13) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.1.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.13) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  sentry-raven (0.14.0) lib/raven/integrations/rack.rb:54:in `call'
  rack-heartbeat (1.0.1) lib/rack/heartbeat.rb:27:in `call'
  railties (4.1.13) lib/rails/engine.rb:514:in `call'
  railties (4.1.13) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  puma (2.12.2) lib/puma/server.rb:539:in `handle_request'
  puma (2.12.2) lib/puma/server.rb:386:in `process_client'
  puma (2.12.2) lib/puma/server.rb:269:in `block in run'
  puma (2.12.2) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by marcellosachs** [comment]
@kriskelly sorry! I accidentally put an unstable feature branch onto develop. Ill make it stable today...
